baseURL: "https://magdelinehuang.com/"
title: Magdeline Huang
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

taxonomies:
  tag: "tags"

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Magdeline Huang
  description: "My digital garden"
  keywords: [Blog, Portfolio, PaperMod]
  author: Magdeline Huang
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/favicon-16x16.png"

  label:
    text: "Magdeline Huang"
    icon:
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Magdeline Huang
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hello world, I'm Magdeline! 👩🏻‍💻"
    Content: Welcome to my digital garden where I document my learnings as a Software Engineer.

  socialIcons:
    - name: github
      url: "https://github.com/xsol05"
    - name: youtube
      url: "https://www.youtube.com/c/MagdelineHuang/featured"
    - name: twitter
      url: "https://twitter.com/magdelinehuang"
    - name: other
      url: "https://mylinks.ai/magdelinehuang"
    # - name: tiktok
    #   url: "https://www.tiktok.com/@magdelinehuang"
    # - name: instagram
    #   url: "https://www.instagram.com/magdelinehuang/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/xsol05/xsol05.github.io/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    # - identifier: about
    #   name: about
    #   url: /about/
    #   weight: 10
    - identifier: archive
      name: archive
      url: /archive/
      weight: 20
    - identifier: tags
      name: tags
      url: /tags/
      weight: 30
    - identifier: search
      name: search
      url: /search/
      weight: 40
    - identifier: changelog
      name: changelog
      url: /changelog/
      weight: 50

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

# For search: https://github.com/adityatelange/hugo-PaperMod/wiki/Features#search-page
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

# Publishing the site
publishDir: "docs"

# Disqus comments
disqusShortname: magdelinehuang
